person:
    personal-details:
        name: ABC
    age: 25
    phone-number: 123214213421
    address:
        address-line1: adsfasdf
        address-line2: sfasdfasd
        state: TS
        pincode: 345435
    account-details:
        bank:
            sbi:
                account-number: 234542353
                balance: 234234
                loan:
                    account-details:
                        account-number: 2342342
                        balance: 346534
            hdfc:
               account-number: 4535334
               balance: 34532
               loan:
                   account-details:
                       account-number: 453453
                       balance: 4534534
            icici:
               account-number: 4534534
               balance: 4353453
               loan:
                    account-details:
                       account-number: 764756745
                       balance: 4567567
	